### PR TITLE
Test2

### PR DESCRIPTION
**Pull request by nairr**
correction for face area fraction calculation. Please feel free to modify it as you will

### CODE REVIEW

**Comment by kel85uk** [comment]
We need face area? How's it different from what was already implemented?

**Comment by nairr** [comment]
We need face area fraction. It was calculated wrongly. Check diff for difference

**Comment by kel85uk** [comment]
Yeah, denom is not updated correctly.

**Comment by kel85uk** [comment]
Thanks for the test and changes. :-)

**Comment by kel85uk** [comment]
Closing this PR as I've already added the changes to the branch. I'd rather avoid the mess of the rebase... Thanks!

**Pull request closed without merging**
